name: openmesh
channels:
  - conda-forge
dependencies:
  - python=3.11
  - netcdf4
  - notebook
  - seaborn
  - folium
  - pycomlink
  - tqdm
  - pip
  - pip:
    - numpy>=1.26
    - pandas>=2.1
    - xarray==2025.3.1
    - scipy
    - matplotlib==3.10.1
    - torch
    - torchvision
    - utm
    - prettytable
    - huggingface_hub
    - poligrain
    - jupyter
    - ipykernel